// This file is auto-generated by @hey-api/openapi-ts

import { type Options, healthCheckHealthGet, getUniqueAuthorsAuthorsGet, getCommitDeviationsCommitsDeviationsGet, getWeeklyActivityActivityWeeklyGet, getWordFrequencyCommitsWordFrequencyGet } from '../sdk.gen';
import { queryOptions } from '@tanstack/react-query';
import type { HealthCheckHealthGetData, GetUniqueAuthorsAuthorsGetData, GetCommitDeviationsCommitsDeviationsGetData, GetWeeklyActivityActivityWeeklyGetData, GetWordFrequencyCommitsWordFrequencyGetData } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const healthCheckHealthGetQueryKey = (options?: Options<HealthCheckHealthGetData>) => createQueryKey('healthCheckHealthGet', options);

/**
 * Health Check
 */
export const healthCheckHealthGetOptions = (options?: Options<HealthCheckHealthGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await healthCheckHealthGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: healthCheckHealthGetQueryKey(options)
    });
};

export const getUniqueAuthorsAuthorsGetQueryKey = (options?: Options<GetUniqueAuthorsAuthorsGetData>) => createQueryKey('getUniqueAuthorsAuthorsGet', options);

/**
 * Get Unique Authors
 * Returns a list of unique commit authors within the date constraints.
 */
export const getUniqueAuthorsAuthorsGetOptions = (options?: Options<GetUniqueAuthorsAuthorsGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getUniqueAuthorsAuthorsGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUniqueAuthorsAuthorsGetQueryKey(options)
    });
};

export const getCommitDeviationsCommitsDeviationsGetQueryKey = (options?: Options<GetCommitDeviationsCommitsDeviationsGetData>) => createQueryKey('getCommitDeviationsCommitsDeviationsGet', options);

/**
 * Get Commit Deviations
 * Returns commits with a significant deviation based on z-score > 2.
 */
export const getCommitDeviationsCommitsDeviationsGetOptions = (options?: Options<GetCommitDeviationsCommitsDeviationsGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCommitDeviationsCommitsDeviationsGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getCommitDeviationsCommitsDeviationsGetQueryKey(options)
    });
};

export const getWeeklyActivityActivityWeeklyGetQueryKey = (options: Options<GetWeeklyActivityActivityWeeklyGetData>) => createQueryKey('getWeeklyActivityActivityWeeklyGet', options);

/**
 * Get Weekly Activity
 * Returns a sum of activity aggregated by day of the week.
 */
export const getWeeklyActivityActivityWeeklyGetOptions = (options: Options<GetWeeklyActivityActivityWeeklyGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getWeeklyActivityActivityWeeklyGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getWeeklyActivityActivityWeeklyGetQueryKey(options)
    });
};

export const getWordFrequencyCommitsWordFrequencyGetQueryKey = (options?: Options<GetWordFrequencyCommitsWordFrequencyGetData>) => createQueryKey('getWordFrequencyCommitsWordFrequencyGet', options);

/**
 * Get Word Frequency
 * Returns the frequency of words in commit messages.
 */
export const getWordFrequencyCommitsWordFrequencyGetOptions = (options?: Options<GetWordFrequencyCommitsWordFrequencyGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getWordFrequencyCommitsWordFrequencyGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getWordFrequencyCommitsWordFrequencyGetQueryKey(options)
    });
};