// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { HealthCheckHealthGetData, HealthCheckHealthGetResponses, GetUniqueAuthorsAuthorsGetData, GetUniqueAuthorsAuthorsGetResponses, GetUniqueAuthorsAuthorsGetErrors, GetCommitDeviationsCommitsDeviationsGetData, GetCommitDeviationsCommitsDeviationsGetResponses, GetCommitDeviationsCommitsDeviationsGetErrors, GetWeeklyActivityActivityWeeklyGetData, GetWeeklyActivityActivityWeeklyGetResponses, GetWeeklyActivityActivityWeeklyGetErrors, GetWordFrequencyCommitsWordFrequencyGetData, GetWordFrequencyCommitsWordFrequencyGetResponses, GetWordFrequencyCommitsWordFrequencyGetErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};

/**
 * Get Unique Authors
 * Returns a list of unique commit authors within the date constraints.
 */
export const getUniqueAuthorsAuthorsGet = <ThrowOnError extends boolean = false>(options?: Options<GetUniqueAuthorsAuthorsGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetUniqueAuthorsAuthorsGetResponses, GetUniqueAuthorsAuthorsGetErrors, ThrowOnError>({
        url: '/authors',
        ...options
    });
};

/**
 * Get Commit Deviations
 * Returns commits with a significant deviation based on z-score > 2.
 */
export const getCommitDeviationsCommitsDeviationsGet = <ThrowOnError extends boolean = false>(options?: Options<GetCommitDeviationsCommitsDeviationsGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetCommitDeviationsCommitsDeviationsGetResponses, GetCommitDeviationsCommitsDeviationsGetErrors, ThrowOnError>({
        url: '/commits/deviations',
        ...options
    });
};

/**
 * Get Weekly Activity
 * Returns a sum of activity aggregated by day of the week.
 */
export const getWeeklyActivityActivityWeeklyGet = <ThrowOnError extends boolean = false>(options: Options<GetWeeklyActivityActivityWeeklyGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetWeeklyActivityActivityWeeklyGetResponses, GetWeeklyActivityActivityWeeklyGetErrors, ThrowOnError>({
        url: '/activity/weekly',
        ...options
    });
};

/**
 * Get Word Frequency
 * Returns the frequency of words in commit messages.
 */
export const getWordFrequencyCommitsWordFrequencyGet = <ThrowOnError extends boolean = false>(options?: Options<GetWordFrequencyCommitsWordFrequencyGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetWordFrequencyCommitsWordFrequencyGetResponses, GetWordFrequencyCommitsWordFrequencyGetErrors, ThrowOnError>({
        url: '/commits/word-frequency',
        ...options
    });
};