// This file is auto-generated by @hey-api/openapi-ts

/**
 * CommitDeviation
 */
export type CommitDeviation = {
    /**
     * Sha
     */
    sha: string;
    /**
     * Title
     */
    title: string;
    /**
     * Additions
     */
    additions: number;
    /**
     * Deletions
     */
    deletions: number;
    /**
     * Total Changes
     */
    total_changes: number;
    /**
     * Z Score
     */
    z_score: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MetricType
 */
export type MetricType = 'commits' | 'additions' | 'deletions' | 'total_changes';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUniqueAuthorsAuthorsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start Date
         */
        start_date?: string;
        /**
         * End Date
         */
        end_date?: string;
    };
    url: '/authors';
};

export type GetUniqueAuthorsAuthorsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUniqueAuthorsAuthorsGetError = GetUniqueAuthorsAuthorsGetErrors[keyof GetUniqueAuthorsAuthorsGetErrors];

export type GetUniqueAuthorsAuthorsGetResponses = {
    /**
     * Response Get Unique Authors Authors Get
     * Successful Response
     */
    200: Array<string>;
};

export type GetUniqueAuthorsAuthorsGetResponse = GetUniqueAuthorsAuthorsGetResponses[keyof GetUniqueAuthorsAuthorsGetResponses];

export type GetCommitDeviationsCommitsDeviationsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start Date
         */
        start_date?: string;
        /**
         * End Date
         */
        end_date?: string;
    };
    url: '/commits/deviations';
};

export type GetCommitDeviationsCommitsDeviationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCommitDeviationsCommitsDeviationsGetError = GetCommitDeviationsCommitsDeviationsGetErrors[keyof GetCommitDeviationsCommitsDeviationsGetErrors];

export type GetCommitDeviationsCommitsDeviationsGetResponses = {
    /**
     * Response Get Commit Deviations Commits Deviations Get
     * Successful Response
     */
    200: Array<CommitDeviation>;
};

export type GetCommitDeviationsCommitsDeviationsGetResponse = GetCommitDeviationsCommitsDeviationsGetResponses[keyof GetCommitDeviationsCommitsDeviationsGetResponses];

export type GetWeeklyActivityActivityWeeklyGetData = {
    body?: never;
    path?: never;
    query: {
        metric_type: MetricType;
        /**
         * Start Date
         */
        start_date?: string;
        /**
         * End Date
         */
        end_date?: string;
        /**
         * Author
         */
        author?: string;
    };
    url: '/activity/weekly';
};

export type GetWeeklyActivityActivityWeeklyGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWeeklyActivityActivityWeeklyGetError = GetWeeklyActivityActivityWeeklyGetErrors[keyof GetWeeklyActivityActivityWeeklyGetErrors];

export type GetWeeklyActivityActivityWeeklyGetResponses = {
    /**
     * Response Get Weekly Activity Activity Weekly Get
     * Successful Response
     */
    200: {
        [key: string]: number;
    };
};

export type GetWeeklyActivityActivityWeeklyGetResponse = GetWeeklyActivityActivityWeeklyGetResponses[keyof GetWeeklyActivityActivityWeeklyGetResponses];

export type GetWordFrequencyCommitsWordFrequencyGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start Date
         */
        start_date?: string;
        /**
         * End Date
         */
        end_date?: string;
    };
    url: '/commits/word-frequency';
};

export type GetWordFrequencyCommitsWordFrequencyGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWordFrequencyCommitsWordFrequencyGetError = GetWordFrequencyCommitsWordFrequencyGetErrors[keyof GetWordFrequencyCommitsWordFrequencyGetErrors];

export type GetWordFrequencyCommitsWordFrequencyGetResponses = {
    /**
     * Response Get Word Frequency Commits Word Frequency Get
     * Successful Response
     */
    200: {
        [key: string]: number;
    };
};

export type GetWordFrequencyCommitsWordFrequencyGetResponse = GetWordFrequencyCommitsWordFrequencyGetResponses[keyof GetWordFrequencyCommitsWordFrequencyGetResponses];

export type ClientOptions = {
    baseUrl: 'https://octopus-app-6mltj.ondigitalocean.app' | (string & {});
};